GET http://localhost:8080/todos
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjgxNDcyMjEsImlzcyI6InRlc3QifQ.kGPQtMred12biu_RSnyrgWqh40ET0kOEhWVzv_n0YBc
